services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT:-5490}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  data:
    driver: local